name: ci

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo Building again again again?
