name: ci

on:
  workflow_dispatch:
    inputs:
      app:
        description: "Which app to deploy"
        type: choice
        options:
          - Panda
          - Rhino
          - Puma

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo Building again again again?
