name: test environment build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - beacon-*

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo Building again
