name: ci

on:
  workflow_run:
    workflows: ["deploy"]
    branches:
      - beacon-*
    types: [completed]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo CI
