name: test environment build

on:
  pull_request:
    branches:
      - beacon-2690-single-repo-pr

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo Building again
