name: deploy

on:
  workflow_dispatch:
    inputs:
      which_panda:
        description: "Please enter a Panda branch from aws-infrastructure to use as a data source."
    branches:
      - beacon-*

jobs:
  two:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          echo Destroy
          echo ${{ inputs.which_panda }}
