name: teardown

on:
  pull_request:
    types:
      - closed
    branches: ["beacon-*"]

jobs:
  two:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo Destroy
      - name: Testing again
        run: echo "Destroy more"
