name: additional

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  two:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo Destroy
      - name: Testing again
        run: echo "Destroy more"
