name: additional

on:
  pull_request:
    branches:
      - beacon-*
  workflow_run:
    workflows: [ci]
    branches: [beacon-54321]
    types: [completed]

jobs:
  two:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo Destroy
      - name: Testing again
        run: echo "Destroy more"
